server:
  port: 9020
spring:
  application:
    name: bdx-zuul
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
      #defaultZone: http://120.79.247.154:6868/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    bdx-backstage-manager: #后台管理
      path: /v1/**  #配置请求url的请求规则
      #url: http://localhost:9000
      serviceId: bdx-backstage-manager  #指定eureka注册中心的服务id
    bdx-user:
      path: /v2/**
      serviceId: bdx-user
    bdx-message:
      path: /v3/**
      serviceId: bdx-message
    bdx-sources:
      path: /v4/**
      serviceId: bdx-sources
    bdx-info:
      path: /v5/**
      serviceId: bdx-info
  sensitive-headers:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
    max-total-connections: 500
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

